name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch name

permissions:
  contents: write    # This is important! Gives write permission

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      
      - name: Build
        run: |
          flutter pub get
          flutter build web --base-href /Movie_Recommendations_App_Flutter/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web